# -*- coding: utf-8 -*-
"""Kaggle_001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hx3xsOfeA0bxneqojDWixFkYVDWXtfpO
"""

import pandas as pd
import numpy as np
from keras.layers import Dense
from keras.models import Sequential
from keras.callbacks import EarlyStopping

df = pd.read_csv('card_transdata.csv', delimiter=',')
df = df.to_numpy()
type(df)
df.shape

predictors = df[:,0:7]
type(predictors)
predictors.shape

target = df[:,7]
target.shape

nodos = predictors.shape[1]
nodos

model =  Sequential()
model.add(Dense(nodos, activation='relu', input_shape=(nodos, )))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(2, activation='relu'))

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

callback = EarlyStopping(monitor='loss', patience=5)

model.fit(predictors, target, batch_size=50, epochs=20, validation_split=0.2, shuffle=1, callbacks=[callback])

model.save("modelvsfraud.h5")